version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=java-api-challenge-postgres-user
      - POSTGRES_PASSWORD=java-api-challenge-postgres-pass
      - POSTGRES_DB=postgres